### ISSUE TITLE
Opening link in new tab causes page loading 

### ISSUE THREAD

**Issue by edvb** [uwigem/wiki2018#10]
When you open a link from the nav bar in a new tab and switch back to the site the page content is replaced with "Page loading..." indefinitely. I am on Firefox 61.

**Comment by kwokwilliam** [comment]
Fixed by adding a small workaround, just a timeout that never resolves if the page is changing:

```javascript
    displayLoadingMessage() {
        this.setState({ loading: true });
        setTimeout(() => {
            this.setState({ loading: false });
        }, 500);
    }
```
