### ISSUE TITLE
Add a Markdown/LaTeX parser

### ISSUE THREAD

**Issue by kwokwilliam** [uwigem/wiki2018#7]
Ideally have it be so simple for the people writing content that they JUST need to write LaTeX/Markdown/Code in a single box and we grab that string and stick it into a single object that is rendered perfectly.

There are libraries that exist for this.

**Comment by edvb** [comment]
I have some experience with markdown and latex so I can help out on this. Are you planning on having a separate web interface for people to paste their markdown into which then converts is all to HTML and sends it to the wiki or just have the wiki convert the markdown and latex itself from markdown files added by people? I've used MathJax before as a LaTex web formatter which works pretty well and is easy to set up, only problem is that it can be pretty slow so you only want to load it on the pages that need it.

**Comment by kwokwilliam** [comment]
mm I was thinking that it would be on all pages with content.

For example, there is a library called [react-markdown](https://rexxars.github.io/react-markdown/) that has support for generating markdown just by providing a VERY LONG `string` as a prop (looks like `<ReactMarkdown source={string} />` so it is very simple.

After a quick search, I think this is *something like* we want to use: [react-markdown-plus](https://www.npmjs.com/package/react-markdown-plus).

I say something like because the package has like 0 downloads and hasn't been updated in a year, so we may want to look for something else, or we have to program our own parser that merges a standalone LaTeX parser and a Markdown parser.

**Comment by kwokwilliam** [comment]
Ooh I found this:

https://github.com/rexxars/react-markdown/issues/10

I think this is the way to go. Don't worry about code syntax highlighting, that part is hard to do, took me like 4 hours to figure it out in my lab. I can add it in later.

**Comment by kwokwilliam** [comment]
I have added a ReactMarkdown and Latex parser to ContentView.js. We may have to insert a code parser. This part is complicated and I can add it in by replicating what I did for my lab's code.
